import './globals.css'
import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import Header from '@/app/components/header'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home | Skippa - Linq',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
