import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Toaster } from "@/app/components/ui/toaster";
import Header from "@/app/components/header";
import AuthProvider from "./context/authProvider";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home | Skippa - Linq",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={raleway.className}>
          <Header />
          {children}
          <Toaster />
        </body>
      </html>
    </AuthProvider>
  );
}
